### ISSUE TITLE
Update Git remote auto

### ISSUE THREAD

**Issue by koxon** [sportarchive/docker-environments#8]
Find a way to get the origin remote URL of the user to update the remote in the sa_site_v2 git submodule.
As of today we need to update things manually

**Comment by Parent5446** [comment]
So unfortunately there is no way to do this from Git (git-clone has an option, but git-submodule does not), and since the repository is outside of the VM (only a sub-folder is actually synced inside the box) it is not really a good idea to attempt to do it from Vagrant. So the only way this can be done is to maybe put something in the Makefile. IMHO the only way to really do it is just document it.

**Comment by koxon** [comment]
ok let's document it in the README.

Thanks

On Mon, Feb 9, 2015 at 12:22 PM, Tyler Romeo <notifications@github.com>
wrote:

> So unfortunately there is no way to do this from Git (git-clone has an
> option, but git-submodule does not), and since the repository is outside of
> the VM (only a sub-folder is actually synced inside the box) it is not
> really a good idea to attempt to do it from Vagrant. So the only way this
> can be done is to maybe put something in the Makefile. IMHO the only way to
> really do it is just document it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sportarchive/docker-environments/issues/8#issuecomment-73549818>
> .
>



-- 
Nicolas Menciere
Founder and CTO
Sport Archive Inc.
